language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: iq2F+TMsqosGpfF91ri1qeGld2kN5RRfoYNiIMYwlAmz2bkB32Wew24WkGMwKg7ViqSZ9ouqmAuKKebZ71xvBhxrGUnMKA/Qkk8d54j9iQjkS/+HI+FPlpoijzmzcY1zFoplks18KbP/oYzfnrgW8ZlF8XWupJOMIb13D+5dO4FDNNgTyCYeNQkn2o3i6HgnTwGXYwkmwnzi7CKekk7UZxiGYTLGBXCTqtTFcG6HtFJ7C6o+0MhZ7sFo8Hy9755KwTYnppo17o1tATV4zG6/WV59tWof1uobbxgERuRuyAfDXKAc7b8w/agw16z4bKcCI/92bJB2qIFahpeRC4svVD6mHfCVH1wOvCnPBAPk6FRdSRUI6kx6cuXyQoe672nHpZEWMOND4t/nJ1I7g8BlFW2OuK1KZYLBa3du9zW1gaDboW5HMmH0yLQQtNU4Ez5s7wuZyPcMspy6vwJ1JYYQACPcYev6Wa2VEK+y6/UmKcyFocaASk4SaNPpGEBhjDFxi8XpCU1mPUJsnTSvEjgaeQ11UCCqlGsUjBsJzKx865ezEPVLdzp3GZB5VEnEpMQ+DHM+eV8eVbLVJKEBlYXdMHa60wDhrC5o2kUHonBzoGiLj0Ozmk66KldQGH82NeAxVSegX+lbL/RYQtM0aKNQaLr9oqslzBEosz/7eefFOXU=
